# Copyright (c) 2021 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# This file contains baseline expectations
# for checked results by checkmetrics tool.
#
# values set specifically for packet.com c1.small worker.

[[metric]]
name = "boot-times"
type = "json"
description = "measure container lifecycle timings"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"boot-times\".Results | .[] | .\"to-workload\".Result"
checktype = "mean"
midval = 0.67
minpercent = 20.0
maxpercent = 10.0

[[metric]]
name = "memory-footprint"
type = "json"
description = "measure container average footprint"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"memory-footprint\".Results | .[] | .average.Result"
checktype = "mean"
midval = 118601.0
minpercent = 5.0
maxpercent = 5.0

[[metric]]
name = "memory-footprint-ksm"
type = "json"
description = "measure container average footprint with KSM"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"memory-footprint-ksm\".Results | .[] | .average.Result"
checktype = "mean"
midval = 54538.11
minpercent = 15.0
maxpercent = 15.0

[[metric]]
name = "blogbench"
type = "json"
description = "measure container average of blogbench write"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"blogbench\".Results | .[] | .write.Result"
checktype = "mean"
midval = 975.0
minpercent = 10.0
maxpercent = 10.0

[[metric]]
name = "blogbench"
type = "json"
description = "measure container average of blogbench read"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"blogbench\".Results | .[] | .read.Result"
checktype = "mean"
midval = 55808.66
minpercent = 10.0
maxpercent = 10.0

[[metric]]
name = "memory-footprint-inside-container"
type = "json"
description = "measure memory inside the container"
# Min and Max values to set a 'range' that
# the median of the CSV Results data must fall
# within (inclusive)
checkvar = ".\"memory-footprint-inside-container\".Results | .[] | .memtotal.Result"
checktype = "mean"
midval = 4139564.0
minpercent = 5.0
maxpercent = 5.0
