#
# Copyright (c) 2020 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0


jobs:
  CLOUD-HYPERVISOR-K8S-E2E-CRIO-MINIMAL:
    passed: 15
  CLOUD-HYPERVISOR-K8S-E2E-CONTAINERD-MINIMAL:
    passed: 15
  CLOUD-HYPERVISOR-K8S-E2E-CRIO-FULL:
    passed: 278
  CLOUD-HYPERVISOR-K8S-E2E-CONTAINERD-FULL:
    passed: 273
  minimal:
    focus:
      - ConfigMap should be consumable from pods in volume
      - InitContainer \[NodeConformance\] should invoke init containers
      - Kubelet when scheduling a busybox command in a pod should printk
      - Projected secret should be consumable in multiple volumes
      - Secrets should be consumable via the environment
      - \[sig-storage\] Downward API volume should update annotations on modification \[NodeConformance\] \[Conformance\]
