#
# Copyright (c) 2022 Ant Group
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Pod
metadata:
  name: hugepage-pod
spec:
  runtimeClassName: kata
  containers:
  - name: hugepage-container
    image: quay.io/prometheus/busybox:latest
    command: ["/bin/sh"]
    args: ["-c", "tail -f /dev/null"]
    volumeMounts:
    - mountPath: /hugepages
      name: hugepage
    resources:
      limits:
        hugepages-1Gi: 1Gi
        memory: 2Gi
      requests:
        hugepages-1Gi: 1Gi
        memory: 2Gi
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
